// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCegti6lISHzLkGbUqlLZjIrpcexTsn604',
    appId: '1:115981118459:web:1d6be648531ec12ca4795e',
    messagingSenderId: '115981118459',
    projectId: 'q4k-1-387e2',
    authDomain: 'q4k-1-387e2.firebaseapp.com',
    storageBucket: 'q4k-1-387e2.appspot.com',
    measurementId: 'G-4XQ8CVX7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc2FbJcYkaUVBKqdeFgVftT9HycavYvEo',
    appId: '1:115981118459:android:291adbc19572d4fea4795e',
    messagingSenderId: '115981118459',
    projectId: 'q4k-1-387e2',
    storageBucket: 'q4k-1-387e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZP8TghNVBZldduyqgxkTWzsVefGzJbE',
    appId: '1:115981118459:ios:8c42560db221a477a4795e',
    messagingSenderId: '115981118459',
    projectId: 'q4k-1-387e2',
    storageBucket: 'q4k-1-387e2.appspot.com',
    iosClientId: '115981118459-uo93ghhq9s4qj2r73rqvqgusi82scvbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.q4k',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZP8TghNVBZldduyqgxkTWzsVefGzJbE',
    appId: '1:115981118459:ios:8c42560db221a477a4795e',
    messagingSenderId: '115981118459',
    projectId: 'q4k-1-387e2',
    storageBucket: 'q4k-1-387e2.appspot.com',
    iosClientId: '115981118459-uo93ghhq9s4qj2r73rqvqgusi82scvbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.q4k',
  );
}
